# Generated by Django 5.0.3 on 2024-05-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_tutorial", "0002_trafficinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficinfo",
            name="icon",
            field=models.CharField(
                choices=[("green", "green"), ("yellow", "yellow"), ("red", "red")],
                default="green",
                max_length=10,
            ),
        ),
    ]
