# Generated by Django 5.0.3 on 2024-05-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_tutorial", "0005_generatealert_generatereport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficlight",
            name="error",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="trafficlight",
            name="function_error",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
